name: Test

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack success
        if: success()
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          status: STARTING
          color: warning

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Test
        run: npm test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          status: FAILED
          color: danger
